# Generated by Django 3.2.4 on 2024-08-23 16:16

import api.v1.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('flag', models.URLField(null=True)),
                ('flag_image', models.ImageField(null=True, upload_to='country/flag/')),
                ('currency_symbol', models.CharField(max_length=50, null=True)),
                ('currency_code', models.CharField(max_length=10, null=True)),
                ('currency_name', models.CharField(max_length=100, null=True)),
                ('short_name', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country_master',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(1, 'ADMIN'), (2, 'SUB_ADMIN'), (3, 'USER')], max_length=20)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('full_name', models.TextField(null=True)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='profile_image/')),
                ('mobile_number', models.CharField(max_length=16)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('mobile_otp', models.CharField(blank=True, max_length=4, null=True)),
                ('email_otp', models.CharField(blank=True, max_length=4, null=True)),
                ('mobile_otp_generate_time', models.DateTimeField(blank=True, null=True)),
                ('email_otp_generate_time', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=250, null=True)),
                ('raw_password', models.CharField(max_length=250, null=True)),
                ('address', models.TextField(null=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField(null=True)),
                ('fcm_token', models.TextField(null=True)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('is_access_updated', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_approved', models.CharField(blank=True, max_length=100, null=True)),
                ('countrymaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.countrymaster')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.role')),
            ],
            options={
                'db_table': 'user_master',
            },
            managers=[
                ('objects', api.v1.manager.CustomUserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='usermaster',
            index=models.Index(fields=['email', 'mobile_number', 'id'], name='user_master_email_03bf9f_idx'),
        ),
    ]
