# Generated by Django 4.2 on 2024-10-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_products_brand_name_alter_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='brand_name',
        ),
    ]
