# Generated by Django 4.2 on 2024-10-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_brands_remove_products_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.brands'),
        ),
        migrations.AlterModelTable(
            name='brands',
            table='brand',
        ),
    ]
